language: elixir
elixir:
  - 1.7.0
  - 1.8.0
  - 1.9.0
otp_release:
  - 20.1
  - 21.0
  - 22.0
matrix:
  exclude:
    - elixir: 1.4.1
      otp_release: 20.0
    - elixir: 1.4.1
      otp_release: 20.1
env:
  global:
    - MIX_ENV=test
before_install:
  - git submodule update --init --recursive
script:
  - "yes | mix do deps.get, deps.compile, compile, coveralls.travis"
